### PR TITLE
a tutorial for setting up miniconda, python, and jupyter notebook.

### PR DESCRIPTION
**Pull request by gayathrimohan01**
for #2

### CODE REVIEW

**Comment by gayathrimohan01** [comment]
@zym1010  Let me know if you want me to add more details

**Review by zym1010 — CHANGES_REQUESTED** [review]
1. change to `.md`, as here we don't need ipynb at all.
2. split the file into four parts. slurm, miniconda, python environment, and jupyter. Name them as `slurm.md`,
`miniconda.md`, `python.md`, and `jupyter.md`. Put them under `/modules`, and then create a file called `jupyter_quickstart.md` under `/tutorials`, and this file should only contain the links to the above mentioned four files.

When writing links, using relative path, such as `[miniconda](../modules/miniconda.md)`.

**Comment by zym1010** [comment]
details added~

**Comment by zym1010** [comment]
main reason for the splitting, is for reuse. Thus, I and other people can improve on separate parts.

Oh, also, create a `/modules/tmux.md`, for tmux.

Thanks!

**Comment by gayathrimohan01** [comment]
@zym1010 I just wanted to confirm with you if this is what you want me to do. I will create two folders in computing resources modules and tutorials. I will split my documents into fours different .md files and upload it in the modules folder. Inside the tutorials folder, I will add a file named jupyter_quickstart.md with the references to the files in modules folder.

**Comment by zym1010** [comment]
@gayathrimohan01 yes that's what I meant.

**Pull request closed without merging**
