### PR TITLE
a tutorial for setting up miniconda, python, and jupyter notebook

### PR DESCRIPTION
**Pull request by gayathrimohan01**

### CODE REVIEW

**Review by zym1010 — CHANGES_REQUESTED** [review]
1. change all double asterisk to backtick, so that they look like code.
2. have numbered or bullet list. Check my recent commit.
3. In `jupyter_quickstart.md`, please use relative link, as I gave in previous comments.

**Comment by gayathrimohan01** [comment]
What do you mean by relative link?

**Comment by zym1010** [comment]
@gayathrimohan01  https://github.com/leelabcnbc/computing-resources/pull/3#pullrequestreview-53080400

**Comment by gayathrimohan01** [comment]
@zym1010 I think I have made the changes that you mentioned in the previous comment. Let me know if there are more changes.

**Comment by zym1010** [comment]
@gayathrimohan01 
i have fixed most of issues. check on what changes I have made and you can also do them next time. thx.

**Comment by zym1010** [comment]
one final thing. You should add corresponding links to modules and tutorials in `README.md`.

**Comment by zym1010** [comment]
@gayathrimohan01 just a reminder.

**Comment by gayathrimohan01** [comment]
I have added the links in the README.md

**Comment by zym1010** [comment]
I fixed some dead links. all is good now. thx.

**Review by zym1010 — APPROVED** [review]

**Pull request merged**
